name: Sync ML -> Shopify (sku_list support)

on:
  workflow_dispatch:
    inputs:
      run_mode:
        description: 'manual | test'
        required: false
        default: 'manual'
  schedule:
    - cron: '0 7 * * *' # 07:00 UTC = 02:00 Bogotá (adjust if needed)

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        run: npm ci

      - name: Run sync script (batch / SKU list / full sync)
        env:
          SHOP_DOMAIN: ${{ secrets.SHOP_DOMAIN }}
          SHOPIFY_ADMIN_TOKEN: ${{ secrets.SHOPIFY_ADMIN_TOKEN }}
          ML_TOKEN: ${{ secrets.ML_TOKEN }}
          TEST_SKU: ${{ secrets.TEST_SKU }}
          FULL_SYNC: ${{ secrets.FULL_SYNC }}
          BATCH_SIZE: ${{ secrets.BATCH_SIZE }}
          SKU_LIST: ${{ secrets.SKU_LIST }}
        run: |
          echo "Starting sync: TEST_SKU=${TEST_SKU:-<none>} FULL_SYNC=${FULL_SYNC:-false}"
          if [ -f sku_list.txt ]; then
            echo "sku_list.txt detected in repo — script will process SKUs from file."
          else
            echo "No sku_list.txt found in repo."
          fi
          node sync-ml-to-shopify.js
 
